//! Fetch → render → publish loop.
//!
//! [`PublishLoop`] ties the three things bellwether does
//! into a single repeating task:
//!
//! 1. Fetch a Windy Point Forecast.
//! 2. Build a [`crate::dashboard::DashboardModel`] from
//!    the forecast, then render it to a 1-bit BMP via
//!    the dashboard SVG builder and
//!    [`crate::render::Renderer`].
//! 3. Publish the BMP to an [`ImageSink`] (the web
//!    crate's `TrmnlState` implements this).
//!
//! Errors on any single tick are logged and swallowed:
//! a one-off Windy outage or transient Pi DNS hiccup
//! must not kill the process. The previously-published
//! image stays served, and the device keeps polling it
//! until the next tick succeeds.
//!
//! The [`ImageSink`] trait lives here for now because
//! it has exactly one consumer (this module). Once a
//! second producer shows up (e.g., an on-demand
//! `/api/refresh` handler or a CLI "render once to
//! disk" command), promote it to its own `crate::sink`
//! module.

#[cfg(test)]
mod tests;

use std::error::Error as StdError;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::Duration;

use chrono::Utc;

use crate::clients::windy::{Client as WindyClient, FetchRequest, WindyError};
use crate::config::RenderConfig;
use crate::dashboard;
use crate::render::{RenderError, Renderer};

/// Opaque sink error type.
pub type SinkError = Box<dyn StdError + Send + Sync>;

// `DeviceTelemetry` and `battery_voltage_to_pct` are
// re-exported from the crate's neutral `telemetry`
// module so downstream callers (`bellwether-web`
// today, anything else tomorrow) keep the
// `bellwether::publish::DeviceTelemetry` import path
// they already had.
pub use crate::telemetry::{DeviceTelemetry, battery_voltage_to_pct};

/// Receives rendered images from a [`PublishLoop`]
/// and, optionally, exposes the latest device
/// telemetry the loop should include in the next
/// render.
///
/// Intentionally abstract so the library doesn't
/// depend on the web crate's concrete `TrmnlState`.
/// The web crate wires `TrmnlState` as the
/// production implementation; tests use an in-memory
/// mock.
pub trait ImageSink: Send + Sync {
    /// Publish a rendered BMP. The `filename` is
    /// generated by the loop and is guaranteed to be
    /// alphanumeric-plus-`._-` (URL-safe); impls need
    /// not re-validate it.
    ///
    /// Errors are reported as a boxed `std::error::Error`
    /// so impls can return whatever structured type
    /// suits them without the library taking a
    /// dependency on their error crate.
    fn publish_image(
        &self,
        filename: String,
        bytes: Vec<u8>,
    ) -> Result<(), SinkError>;

    /// Snapshot of the latest telemetry the sink's
    /// upstream device has posted. Default returns
    /// `DeviceTelemetry::default()` (all `None`) so
    /// existing in-memory mocks don't need changes
    /// and a dev-mode deployment with no real device
    /// simply renders placeholders.
    fn latest_telemetry(&self) -> DeviceTelemetry {
        DeviceTelemetry::default()
    }
}

/// Errors from a single [`PublishLoop::tick_once`].
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum PublishError {
    /// Fetching the forecast from Windy failed.
    #[error("fetching Windy forecast: {0}")]
    Windy(#[from] WindyError),
    /// Rendering the SVG to BMP failed.
    #[error("rendering dashboard: {0}")]
    Render(#[from] RenderError),
    /// Publishing to the sink failed. The inner error
    /// is whatever the sink returned.
    #[error("publishing to sink: {0}")]
    Sink(#[source] SinkError),
}

/// Periodic fetch → render → publish task.
///
/// Construct once at startup and call [`Self::run`] from
/// a `tokio::spawn` (or [`supervise`] for a supervised
/// variant). `run` returns only if the task is cancelled
/// — it loops forever otherwise.
pub struct PublishLoop<S: ImageSink> {
    windy: WindyClient,
    fetch_request: FetchRequest,
    renderer: Renderer,
    render_cfg: RenderConfig,
    sink: S,
    interval: Duration,
    counter: AtomicU64,
}

impl<S: ImageSink> PublishLoop<S> {
    /// Build a new loop. `interval` is the delay between
    /// successive fetches; pass the same cadence the
    /// device polls at (typically from
    /// `TrmnlConfig::Byos::default_refresh_rate_s`).
    #[must_use]
    pub fn new(
        windy: WindyClient,
        fetch_request: FetchRequest,
        renderer: Renderer,
        render_cfg: RenderConfig,
        sink: S,
        interval: Duration,
    ) -> Self {
        Self {
            windy,
            fetch_request,
            renderer,
            render_cfg,
            sink,
            interval,
            counter: AtomicU64::new(0),
        }
    }

    /// Run the loop forever. Cancel by aborting the
    /// tokio `JoinHandle`.
    ///
    /// The first tick fires immediately; subsequent
    /// ticks every `interval`. Any single tick's error
    /// is logged at `warn` and swallowed — transient
    /// Windy / DNS / render errors should not take down
    /// the process.
    pub async fn run(self) {
        let mut ticker = tokio::time::interval(self.interval);
        ticker.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);
        loop {
            ticker.tick().await;
            match self.tick_once().await {
                Ok(filename) => {
                    tracing::info!(%filename, "published image");
                }
                Err(err) => {
                    tracing::warn!(%err, "publish tick failed");
                }
            }
        }
    }

    /// One iteration: fetch, render, publish. Returns
    /// the filename that was published on success.
    ///
    /// Exposed for tests and for a future on-demand
    /// `/api/refresh` handler that wants to trigger a
    /// publish outside the loop's schedule.
    pub async fn tick_once(&self) -> Result<String, PublishError> {
        let forecast = self.windy.fetch(&self.fetch_request).await?;
        let ctx = dashboard::ModelContext {
            tz: self.render_cfg.timezone,
            location: dashboard::astro::GeoPoint {
                lat_deg: self.fetch_request.lat,
                lon_deg: self.fetch_request.lon,
            },
            now: Utc::now(),
            telemetry: self.sink.latest_telemetry(),
        };
        let now_local = ctx.now.with_timezone(&ctx.tz).time();
        let model = dashboard::build_model(&forecast, ctx);
        let svg = dashboard::build_svg(&model, now_local);
        let bmp = self.renderer.render_to_bmp(&svg, &self.render_cfg)?;
        let filename = self.next_filename();
        self.sink
            .publish_image(filename.clone(), bmp)
            .map_err(PublishError::Sink)?;
        Ok(filename)
    }

    /// Generate the next filename. Uses a monotonic
    /// counter so ordering is stable even on RTC-less
    /// devices whose wall clock jumps around between
    /// boot and NTP sync.
    fn next_filename(&self) -> String {
        let n = self.counter.fetch_add(1, Ordering::Relaxed);
        format!("dash-{n:08}.bmp")
    }
}

/// Spawn a background task and log clearly if it ever
/// completes (clean return, panic, or cancel). For
/// loops that are supposed to run forever, a clean
/// return is as much a bug as a panic — both land in
/// the log as `error!` rather than disappearing
/// silently.
///
/// We do **not** auto-restart: a crash-loop would burn
/// through Windy API quota in minutes. If the task
/// dies, the operator investigates and restarts the
/// process manually.
pub fn supervise<F>(
    name: &'static str,
    future: F,
) -> tokio::task::JoinHandle<()>
where
    F: std::future::Future<Output = ()> + Send + 'static,
{
    tokio::spawn(async move {
        let inner = tokio::spawn(future);
        match inner.await {
            Ok(()) => {
                tracing::error!(
                    task = name,
                    "supervised task ended cleanly (unexpected for a \
                     long-running loop); the process will keep serving \
                     but the loop is gone",
                );
            }
            Err(e) if e.is_cancelled() => {
                tracing::info!(task = name, "supervised task cancelled");
            }
            Err(e) => {
                tracing::error!(
                    task = name,
                    error = ?e,
                    "supervised task panicked; the process will keep \
                     serving but the loop is gone",
                );
            }
        }
    })
}
