//! Fetch → render → publish loop.
//!
//! [`PublishLoop`] ties the three things bellwether does
//! into a single repeating task:
//!
//! 1. Fetch a Windy Point Forecast.
//! 2. Render a dashboard SVG to a 1-bit BMP.
//! 3. Publish the BMP to an [`ImageSink`] (the web
//!    crate's `TrmnlState` implements this).
//!
//! The dashboard SVG is a temporary placeholder — a bar
//! whose width tracks the current Celsius temperature.
//! A real layout is tracked in `TODO.md` for a later
//! PR.
//!
//! Errors on any single tick are logged and swallowed:
//! a one-off Windy outage or transient Pi DNS hiccup
//! must not kill the process. The previously-published
//! image stays served, and the device keeps polling it
//! until the next tick succeeds.
//!
//! The [`ImageSink`] trait lives here for now because
//! it has exactly one consumer (this module). Once a
//! second producer shows up (e.g., an on-demand
//! `/api/refresh` handler or a CLI "render once to
//! disk" command), promote it to its own `crate::sink`
//! module.

#[cfg(test)]
mod tests;

use std::error::Error as StdError;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::Duration;

use crate::clients::windy::{
    Client as WindyClient, FetchRequest, Forecast, WindyError,
};
use crate::config::{RenderConfig, WindyParameter};
use crate::render::{RenderError, Renderer};

/// Opaque sink error type.
pub type SinkError = Box<dyn StdError + Send + Sync>;

/// Receives rendered images from a [`PublishLoop`].
///
/// Intentionally abstract so the library doesn't depend
/// on the web crate's concrete `TrmnlState`. The web
/// crate wires `TrmnlState` as the production
/// implementation; tests use an in-memory mock.
pub trait ImageSink: Send + Sync {
    /// Publish a rendered BMP. The `filename` is
    /// generated by the loop and is guaranteed to be
    /// alphanumeric-plus-`._-` (URL-safe); impls need
    /// not re-validate it.
    ///
    /// Errors are reported as a boxed `std::error::Error`
    /// so impls can return whatever structured type
    /// suits them without the library taking a
    /// dependency on their error crate.
    fn publish_image(
        &self,
        filename: String,
        bytes: Vec<u8>,
    ) -> Result<(), SinkError>;
}

/// Errors from a single [`PublishLoop::tick_once`].
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum PublishError {
    /// Fetching the forecast from Windy failed.
    #[error("fetching Windy forecast: {0}")]
    Windy(#[from] WindyError),
    /// Rendering the SVG to BMP failed.
    #[error("rendering dashboard: {0}")]
    Render(#[from] RenderError),
    /// Publishing to the sink failed. The inner error
    /// is whatever the sink returned.
    #[error("publishing to sink: {0}")]
    Sink(#[source] SinkError),
}

/// Periodic fetch → render → publish task.
///
/// Construct once at startup and call [`Self::run`] from
/// a `tokio::spawn` (or [`supervise`] for a supervised
/// variant). `run` returns only if the task is cancelled
/// — it loops forever otherwise.
pub struct PublishLoop<S: ImageSink> {
    windy: WindyClient,
    fetch_request: FetchRequest,
    renderer: Renderer,
    render_cfg: RenderConfig,
    sink: S,
    interval: Duration,
    counter: AtomicU64,
}

impl<S: ImageSink> PublishLoop<S> {
    /// Build a new loop. `interval` is the delay between
    /// successive fetches; pass the same cadence the
    /// device polls at (typically from
    /// `TrmnlConfig::Byos::default_refresh_rate_s`).
    #[must_use]
    pub fn new(
        windy: WindyClient,
        fetch_request: FetchRequest,
        renderer: Renderer,
        render_cfg: RenderConfig,
        sink: S,
        interval: Duration,
    ) -> Self {
        Self {
            windy,
            fetch_request,
            renderer,
            render_cfg,
            sink,
            interval,
            counter: AtomicU64::new(0),
        }
    }

    /// Run the loop forever. Cancel by aborting the
    /// tokio `JoinHandle`.
    ///
    /// The first tick fires immediately; subsequent
    /// ticks every `interval`. Any single tick's error
    /// is logged at `warn` and swallowed — transient
    /// Windy / DNS / render errors should not take down
    /// the process.
    pub async fn run(self) {
        let mut ticker = tokio::time::interval(self.interval);
        ticker.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);
        loop {
            ticker.tick().await;
            match self.tick_once().await {
                Ok(filename) => {
                    tracing::info!(%filename, "published image");
                }
                Err(err) => {
                    tracing::warn!(%err, "publish tick failed");
                }
            }
        }
    }

    /// One iteration: fetch, render, publish. Returns
    /// the filename that was published on success.
    ///
    /// Exposed for tests and for a future on-demand
    /// `/api/refresh` handler that wants to trigger a
    /// publish outside the loop's schedule.
    pub async fn tick_once(&self) -> Result<String, PublishError> {
        let forecast = self.windy.fetch(&self.fetch_request).await?;
        let svg = build_dashboard_svg(&forecast, &self.render_cfg);
        let bmp = self.renderer.render_to_bmp(&svg, &self.render_cfg)?;
        let filename = self.next_filename();
        self.sink
            .publish_image(filename.clone(), bmp)
            .map_err(PublishError::Sink)?;
        Ok(filename)
    }

    /// Generate the next filename. Uses a monotonic
    /// counter so ordering is stable even on RTC-less
    /// devices whose wall clock jumps around between
    /// boot and NTP sync.
    fn next_filename(&self) -> String {
        let n = self.counter.fetch_add(1, Ordering::Relaxed);
        format!("dash-{n:08}.bmp")
    }
}

/// Build the dashboard SVG. Temporary placeholder until
/// a real layout lands — a bar whose width tracks the
/// current Celsius temperature on a 0–40 °C scale.
/// Missing temperature data is rendered as an X overlay
/// so the operator can distinguish it from a real
/// 0 °C reading.
fn build_dashboard_svg(forecast: &Forecast, cfg: &RenderConfig) -> String {
    let (width, height) = (cfg.width, cfg.height);
    let temp = forecast
        .values(WindyParameter::Temp)
        .and_then(|v| v.first().copied().flatten());

    let margin = u32::min(width / 10, 50);
    let avail = width.saturating_sub(margin * 2);
    let bar_h = u32::min(40, height / 2);
    let bar_y = (height / 2).saturating_sub(bar_h / 2);

    let mut body = format!(
        concat!(
            "<rect x=\"{margin}\" y=\"{bar_y}\" ",
            "width=\"{avail}\" height=\"{bar_h}\" ",
            "fill=\"none\" stroke=\"black\" stroke-width=\"2\"/>",
        ),
        margin = margin,
        bar_y = bar_y,
        avail = avail,
        bar_h = bar_h,
    );

    if let Some(kelvin) = temp {
        let celsius = kelvin - 273.15;
        let fraction = (celsius / 40.0).clamp(0.0, 1.0);
        #[allow(
            clippy::cast_precision_loss,
            clippy::cast_possible_truncation,
            clippy::cast_sign_loss
        )]
        let bar_w = (fraction * f64::from(avail)) as u32;
        body.push_str(&format!(
            concat!(
                "<rect x=\"{margin}\" y=\"{bar_y}\" ",
                "width=\"{bar_w}\" height=\"{bar_h}\" fill=\"black\"/>",
            ),
            margin = margin,
            bar_y = bar_y,
            bar_w = bar_w,
            bar_h = bar_h,
        ));
    } else {
        tracing::warn!(
            "no temperature in forecast — rendering \"no data\" overlay",
        );
        let x1 = margin;
        let x2 = margin + avail;
        let y1 = bar_y;
        let y2 = bar_y + bar_h;
        body.push_str(&format!(
            concat!(
                "<line x1=\"{x1}\" y1=\"{y1}\" ",
                "x2=\"{x2}\" y2=\"{y2}\" ",
                "stroke=\"black\" stroke-width=\"3\"/>",
                "<line x1=\"{x1}\" y1=\"{y2}\" ",
                "x2=\"{x2}\" y2=\"{y1}\" ",
                "stroke=\"black\" stroke-width=\"3\"/>",
            ),
            x1 = x1,
            x2 = x2,
            y1 = y1,
            y2 = y2,
        ));
    }

    format!(
        concat!(
            "<svg xmlns=\"http://www.w3.org/2000/svg\" ",
            "width=\"{w}\" height=\"{h}\" viewBox=\"0 0 {w} {h}\">",
            "<rect width=\"{w}\" height=\"{h}\" fill=\"white\"/>",
            "{body}",
            "</svg>",
        ),
        w = width,
        h = height,
        body = body,
    )
}

/// Spawn a background task and log clearly if it ever
/// completes (clean return, panic, or cancel). For
/// loops that are supposed to run forever, a clean
/// return is as much a bug as a panic — both land in
/// the log as `error!` rather than disappearing
/// silently.
///
/// We do **not** auto-restart: a crash-loop would burn
/// through Windy API quota in minutes. If the task
/// dies, the operator investigates and restarts the
/// process manually.
pub fn supervise<F>(
    name: &'static str,
    future: F,
) -> tokio::task::JoinHandle<()>
where
    F: std::future::Future<Output = ()> + Send + 'static,
{
    tokio::spawn(async move {
        let inner = tokio::spawn(future);
        match inner.await {
            Ok(()) => {
                tracing::error!(
                    task = name,
                    "supervised task ended cleanly (unexpected for a \
                     long-running loop); the process will keep serving \
                     but the loop is gone",
                );
            }
            Err(e) if e.is_cancelled() => {
                tracing::info!(task = name, "supervised task cancelled");
            }
            Err(e) => {
                tracing::error!(
                    task = name,
                    error = ?e,
                    "supervised task panicked; the process will keep \
                     serving but the loop is gone",
                );
            }
        }
    })
}
